Dockerfile, website/README.md, website/build-deploy-github-pages.yml, website/package.json
Implements [AB#1677](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/1677)
To ensure all doc changes are relfected on the site. https://amido.github.io/stacks/
Through Devops pipeline. Private to Amido. Anyone can contribute to the documentation.
https://github.com/amido/stacks/commit/db55ec99e2cf2b233ac7458bda9c96fcc51efbbb
Write some epic information in the docs and watch it zoom to a space near you!
=> task: github pages auto publish

docs/getting_started_demo.md, docs/infrastructure_code.md
Expaned on getting started guide
=> chore: docs for getting started guide

docs/getting_started_demo.md
include a jenkins section in the docs as v0 to signify to users its available
=> fix: docs jenkins update

docs/getting_started_demo.md
formatting fixed for tree layout
=> fix: formatting for getting started guide

README.md, docs/cli_testing_frameworks.md
Update the links to the source repos and supporting packages for the love of open source.
More information for the world!
<insert keyboard cat here>
=> docs: landing readme and cli

docs/getting_started_demo.md
good catch by @jpbsheppard 
Render code block with lang bash
=> docs: rendering content in bash code

docs/getting_started_dev_java.md
=> Minor text update

docs/workloads/aws/workloads_aws_readme.md
=> Testing ability to update pages

src/pages/index.js, src/pages/styles.module.css
=> Update Homepage styles

src/pages/index.js, src/pages/styles.module.css
=> Updated Ui

README.md
=> Removed section fromo main readme

docs/testing/dotnet_testing_selenium.md, docs/workloads/azure/backend/netcore/architecture/testing/consummer_driven_contract_testing_netcore.md, docs/workloads/azure/backend/netcore/architecture/testing/testing_scope_netcore.md, docs/workloads/azure/backend/netcore/introduction_netcore.md, docs/workloads/azure/backend/netcore/logging_netcore.md, docs/workloads/azure/backend/netcore/quickstart/create_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/requirments_netcore.md
=> Updated .Net to .NET

src/pages/HideNavigation.tsx
=> Fixed Hide navigation Bug

docs/workloads/azure/frontend/browser_support.md, docs/workloads/azure/frontend/cli_webapp_frameworks_csr.md, docs/workloads/azure/frontend/cli_webapp_frameworks_ssr.md, docs/workloads/azure/frontend/ide-node.mdx, docs/workloads/azure/frontend/pipeline_csr.md, docs/workloads/azure/frontend/pipeline_ssr.md, src/pages/HideNavigation.tsx, src/pages/styles.module.css
=> Fixed Small Screen aligment

robots.txt
=> update robot file

.markdownlint.json, docs/code_of_conduct.md, docs/infrastructure/azure/core_infrastructure.md, docs/infrastructure/azure/pipelines/azure_devops.md, docs/infrastructure/introduction.md, docs/testing/cli_testing_frameworks.md, docs/testing/performance_testing_gatling.md, docs/workloads/aws/workloads_aws_readme.md, docs/workloads/azure/backend/java/execute_karate_api_tests.md, docs/workloads/azure/backend/java/intro_java.md, docs/workloads/azure/backend/java_cqrs/execute_karate_api_tests.md, docs/workloads/azure/backend/java_cqrs/intro_java_cqrs.md, docs/workloads/azure/backend/netcore/architecture/swagger_configuration/configure_swagger_ui_netcore.md, docs/workloads/azure/backend/netcore/introduction_netcore.md, docs/workloads/gcp/workloads_gcp_readme.md, docs/workloads/workloads.md
=> Fixed pagination by removing next and/or previous on certain pages

static/robots.txt
=> fixed the url to sitemap.xml in robots.txt

docs/workloads/azure/backend/java/testing_java.md, docs/workloads/azure/backend/java_cqrs/testing_java_cqrs.md
=> Delete a typo

docusaurus.config.js, package-lock.json, package.json
=> Add analytics tag on the GitHub pages

static/robots.txt
Fix robots.txt - unlock pages from indexing
=> Fix robots.txt - unlock pages from indexing

README.md, docs/infrastructure/azure/pipelines/azure_devops.md, docs/workloads/azure/frontend/CSR/getting_started_csr.md, docs/workloads/azure/frontend/SSR/contentful_integration.md, docs/workloads/azure/frontend/SSR/getting_started_ssr.md
=> fixing broken links and changing csr and ssr repo links

docs/workloads/azure/backend/netcore/architecture/nuget_dependencies.md, docs/workloads/azure/backend/netcore/architecture/nuget_dependencies_repositories.md, sidebars.js
=> Added nuget repository dependencies page

docs/infrastructure/introduction.md, docs/testing/java_testing_serenity_bdd.md, docs/workloads/azure/backend/java/execute_karate_api_tests.md, docs/workloads/azure/backend/java/execute_serenity_api_tests.md, docs/workloads/azure/backend/java_cqrs/execute_karate_api_tests.md, docs/workloads/azure/backend/java_cqrs/execute_serenity_api_tests.md, docs/workloads/azure/backend/java_cqrs/intro_java_cqrs.md, docs/workloads/azure/backend/netcore/introduction_netcore.md, docs/workloads/azure/frontend/SSR/getting_started_ssr.md, docs/workloads/azure/frontend/SSR/pipeline_ssr.md, src/pages/Components/ResponsivePlayer/ResponsivePlayer.tsx, src/pages/index.js
=> Changed the links to vimeo ones

src/pages/index.js
=> Minor text tweaks

src/pages/index.js
=> Remove erroneous quotes

src/pages/index.js
=> Minor change to copy

src/pages/index.js
=> Updated the 'Get started with Amido Stacks' intro

docs/workloads/azure/backend/java/scaffolding_java.md
Add video content for java. Describes creating new application using maven archetypes.
See the `/docs/workloads/azure/backend/java/scaffolding_java`
=> feat: add java video content

docs/workloads/azure/backend/netcore/quickstart/web_api/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api/create_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/create_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs_events/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs_events/create_project_netcore.md
3904 - Fix documentation inconsistencies
[AB#3904](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/3904)
Change docs based on feedback
=> Fix documentation inconsistencies

docs/workloads/azure/backend/java/requirements_java.md, docs/workloads/azure/backend/java/scaffolding_java.md
Post-review changes for java HowTo.
Changes requested by Simon.
=> feat: java howto  - post review changes

docs/workloads/azure/backend/netcore/quickstart/web_api/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs_events/build_and_run_project_netcore.md
3931 - Add clarifications to dotnet docs
Add clarifications to dotnet docs around the expected path when running the application locally
[AB#3931](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/3931)
=> Add clarifications to dotnet docs

docs/workloads/azure/backend/java/architecture/dependency_api_java.md, docs/workloads/azure/backend/java/architecture/dependency_commons_java.md, docs/workloads/azure/backend/java/architecture/dependency_cosmos_java.md, docs/workloads/azure/backend/java/architecture/dependency_cqrs_java.md, docs/workloads/azure/backend/java/architecture/dependency_messaging_java.md, docs/workloads/azure/backend/java/architecture/dependency_parent_java.md, docs/workloads/azure/backend/java/architecture/dependency_servicebus_java.md, docs/workloads/azure/backend/java/architecture/java_cqrs/structure_java_cqrs.md, docs/workloads/azure/backend/java/architecture/maven_modules_java.md, docs/workloads/azure/backend/java/architecture/web_api/structure_java.md, docs/workloads/azure/backend/java/quickstart_java.md, docs/workloads/azure/backend/java/requirements_java.md, docs/workloads/azure/backend/java/scaffolding_java.md, sidebars.js, versions.js
Changes in the documentation cased by introducing Java modularity.
=> feat: modularity documentation

Dockerfile
Refactor the development dockerfile to use a distroless base image. This image is only used for local development purposes and is not published or run in production.
To reduce security vulnerabilities raised by Snyk
* Followed the example from the distroless image repo: https://github.com/GoogleContainerTools/distroless/blob/main/examples/nodejs/Dockerfile
I have successfully built and executed the image locally:
```
PS C:\repos\github\amido\stacks\amido.github.io> docker build . -t amido.github.io
[+] Building 51.4s (13/13) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                                                                          0.0s
=> => transferring dockerfile: …
```
=> chore: refactor dockerfile to use distroless image

docs/workloads/azure/backend/java/quickstart_java.md
=> fix: post-QA fix

docs/workloads/azure/backend/architecture_overview.md, sidebars.js
Adds a new page containing the new video with the architecture overview (language-agnostic).
The second video has been already updated directly on Vimeo without a link change, so no update is required for it.
=> feat: add the language agnostic architecture overview

sidebars.js
Move Architecture Overview video to a new Architecture section.
As per discussion with Simon during the last demo session.
=> fix: move Architecture Overview video to a new Architecture section.

docs/workloads/azure/backend/netcore/quickstart/web_api/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api/create_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/configure_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/create_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs_events/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs_events/configure_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs_events/create_project_netcore.md, docs/workloads/azure/backend/netcore/requirments_netcore.md, sidebars.js
Multiple fixes to the .NET docs and clarifications. Better formatting of information and naming.
All fixes were part of issues raised by Simon and Jack
=> .NET documentation fixes

docs/index.md
=> fixed intro url for workloads

docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs_events/configure_project_netcore.md
[AB#4519](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/4519) Update README to reflect Secret requirements for AWS SQS
Update README to reflect Secret requirements for AWS SQS
Update README to reflect Secret requirements for AWS SQS
N/A
=> AB#4519 Update README to reflect Secret requirements for AWS SQS

src/pages/index.js
[AB#4509](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/4509) Refactor Public Facing Documentation
Update landing page to have the options restructured to have the language / framework selected first.
If this page is intended to be developer focused then the language and workload is more important than the cloud provider.
Ran locally and ensured the correct documents were displayed when each selection was made.
=> AB#4509 Refactor Public Facing Documentation

docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/configure_project_netcore.md
Update docs to include information on DynamoDB
Add description of DynamoDB usage/configuration
=> Update DynamoDB docs

docs/workloads/azure/backend/netcore/quickstart/web_api/create_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/create_project_netcore.md
Add CiCd provider option to the package
📲 What
Add CiCd provider option to the package
🤔 Why
Enable better context for exclusions based around both CICD and cloud provider.
=> Add CiCd provider option to the package

docs/developer/developer_patterns_readme.md, docs/developer/java/patterns/java_mapstruct_mapping.md, docs/developer/java/patterns/java_swagger_annotations.md, sidebars.js
Implements Stacks Cycle 9 Azure DevOps #4744
Added a new "Development Patterns" section, some additional structure and model pages for "MapStruct" and a place holder for "Swagger Annotations".
To explain how to remove code boilerplate.
See ADR #31 - Reducing Java Boilerplate Code
N/A
=> feat: New "Development Patterns" Section & "MapStruct" docs section - 4744

docs/workloads/aws/backend/java/define_aws_secrets_java.md, docs/workloads/aws/backend/java/setting_up_dynamodb_locally_java.md, docs/workloads/aws/backend/java/setting_up_xray_daemon_locally_java.md, docs/workloads/common/backend/java/maven_spring_profiles.md, sidebars.js
feat: Added Dynamo DB emulator page
Added page on how to run the DynamoDB emulator and create initial Menu table
To further the Stacks roadmap.
See ADR
N/A
`npm run lint`
=> feat: Added Dynamo DB emulator page

docs/workloads/aws/backend/java/setting_up_dynamodb_locally_java.md, docs/workloads/common/backend/java/maven_spring_profiles.md
Updates to DynamoDB and Maven Profile sections
Keep documentation up to date
=> feat : Documentation updates

docs/workloads/common/backend/java/architecture/dependency_api_java.md, docs/workloads/common/backend/java/architecture/dependency_commons_java.md, docs/workloads/common/backend/java/architecture/dependency_cqrs_java.md, docs/workloads/common/backend/java/architecture/dependency_messaging_java.md, docs/workloads/common/backend/java/architecture/dependency_parent_java.md
=> getting rid of artifactory

docs/workloads/aws/backend/java/setting_up_dynamodb_locally_java.md
=> Documentation updates

docs/workloads/aws/backend/java/define_aws_secrets_java.md, docs/workloads/aws/backend/java/setting_up_dynamodb_locally_java.md
=> Added property settings for refresh

docs/nx/workspace/init.md, docs/nx/workspace/plugin-information.md
=> docs(nx): update workspace/init with pipeline changes

docs/nx/azure-react/generator-app-insights-web.md, docs/nx/azure-react/plugin-information.md, docs/nx/nx_monorepo.md, sidebars.js
=> docs: updated NX docs with azure react plugin docs

docs/nx/next/infra.md, docs/nx/next/init.md, docs/nx/next/plugin-information.md
Add OpenTelemetry information to next/infrastructure generator.
=> add OpenTelemetry information to next/infrastructure generator

docs/nx/next/init-deployment.md, docs/nx/next/init.md, docs/nx/next/next-auth-redis-deployment.md, docs/nx/next/next-auth-redis.md, docs/nx/next/plugin-information.md, docs/nx/nx_monorepo.md, docs/nx/workspace/init.md
5755 📲 What
Updates nx docs for next plugin to reflect changes made by splitting infra generators and stacks config inside nx.json
Further improve stacks by making executions modular and assuming less, single responsibility and giving more control to the developer.
=> docs(next): update new stacks structure and split infra generators

docs/nx/next/init-deployment.md
5755 📲 What
Update init-deployment to reflect changes made to deployment code structure.
Reflect new codebase updates and behaviour
Update docs
=> docs(next): update init-deployment to reflect changes in structure

.spelling, docs/nx/azure-node/app-insights-deployment.md, docs/nx/azure-node/app-insights.md, docs/nx/azure-node/plugin-information.md
5770 📲 What
Add deployment generator docs to azure-node documentation.
Reflect new codebase updates and behaviour
Update docs
=> docs(azure-node): update docs with deployment generator

docs/nx/nx_monorepo.md, docs/nx/rest-client/openapi-client.md, docs/nx/rest-client/plugin-information.md
Adds openapi-client generator to rest-client plugin for FE Nx documentation.
Implements [6091](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/6091)
Updated to reflect new feature in Stacks FE.
=> docs: add openapi-client generator to rest-client plugin

docs/nx/next/plugin-information.md, docs/nx/nx_monorepo.md
Update the Nx homepage and nx next page
To reflect changes in the removal of next auth redis
=> Removal of redis and minor updates to nx homepage

README.md
Add instructions on what this repository is for and how to make changes to the documentation.
This makes it easier for new users to contribute to the Stacks documentation.
=> docs: add instructions to readme

docs/workloads/azure/data/components/infrastructure/core_data_platform_azure.md, docs/workloads/azure/data/intro_data_azure.md, docs/workloads/azure/data/repository_data_azure.md
Minor update for Data Platform docs.
To be consistent with the main repo: stacks-azure-data.
MD files update.
=> feat: data platform docs update - 6362

docs/nx/nx_monorepo.md, src/pages/index.js
To make is easier for users getting started with an Nx Stacks workspace.
=> docs: add detail to the instructions to set up an Nx Stacks workspace

docs/workloads/azure/data/getting_started/etl_pipelines_deployment_azure.md, docs/workloads/azure/data/getting_started/example_data_source.md, sidebars.js
Update regarding example dataset used in data platform.
To reflect updates.
Documentation update.
Reviewed on local server.
Reviewed on local server.
=> ingest example data source update

docs/nx/next/init.md
=> feat(): added react-axe info to the existing init docs

docs/workloads/azure/data/etl_pipelines/datastacks.md, docs/workloads/azure/data/getting_started/etl_pipelines_deployment_azure.md, docs/workloads/azure/data/requirements_data_azure.md
Data Platform documentation update.
6588
md files
`npm run build` & `npm run test`
`npm run build` & `npm run test`
=> feat: data docs var groups update - 6588

docs/workloads/azure/data/architecture/repository_data_azure.md
Docs update
Docs update
Docs update
Docs update
Docs update
=> update repo structure doc

docs/module_federation/nextjs_plugin.md, sidebars.js
Add documentation on setting up NextJs module federation with Stacks
=> feat(): add module federation docs

docs/workloads/azure/data/getting_started/etl_pipelines_deployment_azure.md, docs/workloads/azure/data/getting_started/shared_resources_deployment_azure.md
Docs update
Docs update
Docs update
Tested locally
npm run lint
=> Data docs: Add review section

build-deploy-github-pages.yml
Update Github organisation to Enasono from amido 
Github organisation have changed from amido to ensono and reference to repositories are needed to be updated 
=> fix: updated amido to endpoint

docs/workloads/azure/data/getting_started/generate_project.md
[Fix: scaffold example URL]
Fix URL to scaffold example file.
Update reference to main branch.
Updated markdown
Updated markdown
Test new link
=> Fix: scaffold example URL

docs/workloads/azure/data/etl_pipelines/datastacks.md, docs/workloads/azure/data/getting_started/etl_pipelines_deployment_azure.md
Updated usage of poetry to use poetry run rather than poetry shell.
Avoids confusion of users who might start in the middle of an example and not have the shell activated
N/A
N/A
Follow examples provided
=> Feat: Updated poetry usage

docs/getting_started/create-stacks-workspace/plugin-information.md, docs/getting_started/setup.md, src/components/Picker/Picker.tsx
remove client side text in the drop down menu and add in text to the docs
=> fix: remove client side text and add in text to the docs

docs/getting_started/create-stacks-workspace/plugin-information.md, docs/getting_started/next/plugin-information.md, docs/getting_started/setup.md, docs/getting_started/workspace/init-deployment.md, docs/getting_started/workspace/plugin-information.md, docs/linting/eslint.md, docs/module_federation/nextjs_plugin.md, docs/testing/testing_in_nx/frontend_testing_in_nx.md
=> fix(): fix broken create-stacks-workspace link

docs/getting_started/workspace/init.md, docs/linting/eslint.md, docs/workloads/azure/data/getting_started/generate_project.md, docs/workloads/azure/data/requirements_data_azure.md, docs/workloads/azure/frontend-archived/CSR/getting_started_csr.md, docs/workloads/azure/frontend-archived/SSR/getting_started_ssr.md, docs/workloads/gcp/workloads_gcp_readme.md, docusaurus.config.js, src/components/Picker/Picker.tsx
- change to relative path on the documentation links
- change getting started link from the footer to the docs
-
=> fix: change to relative path on the documentation links

docs/workloads/azure/data/etl_pipelines/testing_data_azure.md, docs/workloads/azure/data/getting_started/etl_pipelines_deployment_azure.md
=> Fix: data testing formatting

sidebars.js, src/components/Picker/Picker.tsx
Fixing the path when selecting Java on "What can you do with Stacks?"
Goes to an error page
Fix Path
=> Fix: fix path when selection java

docs/storybook/storybook_stacks.md
=> fix(): make link more prominent

docs/module_federation/nextjs_plugin.md
Updates to federated module docs following stacks lab session.
* Ensure app router is not used when creating header app
* Fix linting issue due to import ordering
* Other issues
=> feat(): update docs

docusaurus.config.js, static/CNAME, static/robots.txt
=> feat(): change sitemap path to stacks.ensono.com

docs/code_of_conduct.md
Code of Conduct grammar updates from lab session
=> fix(): correct grammar

docs/workloads/azure/data/requirements_data_azure.md
updated readme to include service connections
Also had to fix line ending otherwise i couldn't commit
=> 6819-added service connections to readme

src/components/EnsonoStacksImage/EnsonoStacksImage.module.css
Title is misaligned on mobile
Use flex to align title correctly
=> fix(): use flex to align title correctly

src/components/Picker/Picker.module.css
Placeholder text too big on mobile
Change font size for mobile
=> fix(): change mobile font size

docusaurus.config.js
Feedback to adjust the header link to homepage
=> fix(): header logo to homepage

src/components/EnsonoStacksImage/EnsonoStacksImage.module.css
6981, 6989 - Add gradient to hero background and left align hero content.
=> fix(): add gradient to hero and left align content

docs/getting_started/setup.md
=> chore(): Stacks to Ensono Stacks

src/theme/ErrorPageContent.js
Rename the file name as it was not picking up the page not found when doing to an unpathed url 
=> fix(): rename file name to ErrorPageContent

docs/workloads/azure/data/requirements_data_azure.md
Added github token details on what it is and why its needed
Within this the UsePythonVersion in data would fail 
Updated requirements_data_azure.md and ran lint locally.
=> bug 6995 - added documentation for github token

asciidoc/linting/eslint.adoc
=> feat(): add linting doc

asciidoc/getting_started/cypress/accessibility.adoc, asciidoc/getting_started/cypress/executor.adoc, asciidoc/getting_started/cypress/init-deployment.adoc, asciidoc/getting_started/cypress/init.adoc, asciidoc/getting_started/cypress/plugin-information.adoc
=> feat: add Cypress asciidocs

asciidoc/getting_started/azure-react/generator-app-insights-web.adoc, asciidoc/getting_started/azure-react/plugin-information.adoc
=> feat(): Add azure-react to asciiDoc

asciidoc/getting_started/azure-node/plugin-information.adoc, asciidoc/getting_started/azure-react/generator-app-insights-web.adoc, asciidoc/getting_started/logger/plugin-information.adoc, asciidoc/getting_started/logger/winston.adoc
=> chore(): add logger to asciidoc

docs/workloads/azure/data/getting_started/dev_quickstart_data_azure.md
Added env var to docs setup following updates.
Docs update.
Docs update.
Docs update.
npm run lint
=> Data dev setup - add env var

asciidoc/getting_started/workspace/init-deployment.adoc, asciidoc/getting_started/workspace/init.adoc, asciidoc/getting_started/workspace/plugin-information.adoc
7023 - add workspace plugin docl
=> feat(): add workspace plugin doc

asciidoc/getting_started/plugin-name/executor-generator-template.adoc, asciidoc/getting_started/plugin-name/plugin-information.adoc
=> chore(): add plugin-name to asciidoc

asciidoc/getting_started/rest-client/bump-version.adoc, asciidoc/getting_started/rest-client/client-endpoint.adoc, asciidoc/getting_started/rest-client/http-client.adoc, asciidoc/getting_started/rest-client/openapi-client..adoc, asciidoc/getting_started/rest-client/plugin-information.adoc
7022 - add rest client plugin adoc
=> feat(): add rest client adoc

asciidoc/developer/developer_patterns_readme.adoc, asciidoc/developer/java/patterns/java_app_layering.adoc, asciidoc/developer/java/patterns/java_mapstruct_mapping.adoc, asciidoc/developer/java/patterns/java_swagger_annotations.adoc
=> feat(): add developer adoc

asciidoc/infrastructure/azure/core_infrastructure.adoc, asciidoc/infrastructure/azure/pipelines/azure_devops.adoc, asciidoc/infrastructure/introduction.adoc
=> feat(): add infra adoc

asciidoc/workloads/azure/backend/java/testing/execute_karate_api_tests.adoc, asciidoc/workloads/azure/backend/java/testing/execute_serenity_api_tests.adoc, asciidoc/workloads/azure/backend/java/testing/testing_java.adoc
Docs here: docs/workloads/azure/backend/java/testing
converted to asciidoc
=> feat: covert java test docs

asciidoc/workloads/workloads.adoc
=> feat(): add workloads adoc

asciidoc/workloads/azure/backend/netcore/testing/functional_testing_netcore.adoc
Converted netcore testing doc to asciidoc
=> feat: convert netcore testing doc

asciidoc/workloads/azure/backend/java/architecture/dependency_cosmos_java.adoc, asciidoc/workloads/azure/backend/java/architecture/dependency_servicebus_java.adoc
=> chore(): add azure/backend/netcore/architecture asciidoc

asciidoc/workloads/gcp/workloads_gcp_readme.adoc
=> feat(): add gcp adoc

asciidoc/workloads/common/backend/java/architecture/java_cqrs/architecture_java_cqrs.adoc, asciidoc/workloads/common/backend/java/architecture/java_cqrs/structure_java_cqrs.adoc
Converted java_cqrs docs to asciidoc
=> feat: convert java_cqrs docs

asciidoc/workloads/common/backend/java/ide_java.adoc, asciidoc/workloads/common/backend/java/intro_java.adoc, asciidoc/workloads/common/backend/java/maven_spring_profiles.adoc, asciidoc/workloads/common/backend/java/scaffolding_java.adoc
Converted the common backend java docs to asciidoc
=> feat: convert common backend java docs

asciidoc/testing/testing_in_nx/playwright_accessibility_testing.adoc, asciidoc/testing/testing_in_nx/playwright_nx.adoc, asciidoc/testing/testing_in_nx/playwright_visual_testing.adoc, asciidoc/testing/testing_in_nx/playwright_visual_testing_applitools.adoc
Convert playwright nx docs to asciidoc
=> feat: convert playwright docs

docs/workloads/azure/data/data_engineering/data_quality_azure.md
Added documentation around outputting the DQ validation results as delta tables.
[AB#6364](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/6364) - Data Quality Monitoring & Alerting - Results Table
Docs
Docs
n/a
n/a
=> feat: Data Quality Validation Results Table - 6364

asciidoc/stackscli/project_settings.adoc, asciidoc/stackscli/runtime_config.adoc, asciidoc/stackscli/usage.adoc
Converted remaining stackscli docs to asciidoc
=> feat: convert stackscli docs

blog/index.md, docusaurus.config.js
=> feat(): add blog page and blog

docs/workloads/azure/data/getting_started/fabric_deployment_guide.md
Update heading numbering in Fabric documentation page.
=> Fix 7125: Fabric docs numbering

src/components/TechSupportedByStacks/TechSupportedByStacks.tsx
Changed the tech stack logo's to links instead of performing a search
=> fix: change logos to links

docs/workloads/azure/data/getting_started/ingest_pipeline_deployment_azure.md, docs/workloads/azure/data/getting_started/processing_pipeline_deployment_azure.md
=> update examples in the docs

asciidoc/workloads/azure/data/getting_started/fabric_deployment_guide.adoc, docs/workloads/azure/data/getting_started/fabric_deployment_guide.md
Update to data docs for Fabric now it is in general availability.
Update docs.
Update docs.
Update docs.
npm run lint, test on local server.
=> Fabric documentation updates

asciidoc/workloads/azure/data/getting_started/core_data_platform_deployment_azure.adoc, docs/workloads/azure/data/getting_started/core_data_platform_deployment_azure.md
Docs update - remove option to deploy without private networking, as this is not available yet.
Docs update.
Docs update.
Docs update.
Docs update.
=> Remove private network false option

asciidoc/testing/testing_in_nx/playwright/playwright_nx.adoc, asciidoc/workloads/azure/frontend/plugins/playwright/executor.adoc, docs/getting_started/playwright/executor.md, docs/getting_started/playwright/init.md, docs/testing/testing_in_nx/playwright_nx.md
Updates docs to reflect changes to playwright generator
Changes to playwright generator has changed executors used and directory structure
=> feat: update playwright docs to reflect generator changes

.github/workflows/deployment.yml
=> chore: update github workflow node version

asciidoc/workloads/azure/backend/netcore/quickstart/web_api/create_project_netcore.adoc, asciidoc/workloads/azure/backend/netcore/quickstart/web_api_cqrs/create_project_netcore.adoc, docs/workloads/azure/backend/netcore/quickstart/web_api/create_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/create_project_netcore.md
Updated .NET stacks commands to ensure functionality as some were using deprecated methods. Also, some of the copyable commands were calling incorrect template short names. 
Keep the documentation honest and functional.
N A
N/A
N/A
=> Fix: Update .NET stacks commands to ensure functionality

asciidoc/testing/performance_testing_gatling.adoc, asciidoc/workloads/azure/backend/java/quickstart_java.adoc, asciidoc/workloads/azure/backend/java/requirements_java.adoc, asciidoc/workloads/azure/data/getting_started/requirements_data_azure.adoc, asciidoc/workloads/common/backend/java/ide_java.adoc
=> chore:updating docs to reflect java 17 version upgrade

docs/workloads/azure/backend/netcore/architecture/swagger_configuration/configure_swagger_netcore.md
Update external swagger documentation to reference OpenAPI
=> refactor: 8268 - update external swagger configuration

docs/workloads/azure/backend/netcore/architecture/data_storage_comsosdb_netcore.md
Clean up the cosmos db documentation
=> refactor: 8268 tidy up cosmos db doc

docs/workloads/azure/backend/netcore/infrastructure_aws_netcore.md, docs/workloads/azure/backend/netcore/infrastructure_netcore.md, docs/workloads/azure/backend/netcore/introduction_netcore.md, docs/workloads/azure/backend/netcore/pipeline_gha_netcore.md, docs/workloads/azure/backend/netcore/pipeline_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api/create_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/build_and_run_project_netcore.md, docs/workloads/azure/backend/netcore/quickstart/web_api_cqrs/create_project_netcore.md, sidebars.js
Add YouTube tutorials to .NET Stacks documentation.
Give improved documentation experience for clients.
Added ReactPlayed to .NET Stacks documentation and link to relevant YouTube videos.
=> 8099 - Add YouTube tutorials to .NET Stacks documentation

docs/workloads/azure/backend/netcore/infrastructure_netcore.md, docs/workloads/azure/backend/netcore/pipeline_gha_netcore.md, docs/workloads/azure/backend/netcore/pipeline_netcore.md
Update Azure links to be for Azure
Videos finally got uploaded so need including.
=> 8099 - Update Azure links to be for Azure

.spelling, README.md
README update:
- Fix links
- Add known words to `.spelling`
Quality of Life
=> docs(): Update README, spelling
